name: akilasatolu-v5-prod

services:
    web:
        container_name: akilasatolu-v5-prod-web
        build:
            context: .
            dockerfile: Dockerfile
            args:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_REGION: ${AWS_REGION:-ap-northeast-1}
                S3_BUCKET_BLOG: ${S3_BUCKET_BLOG}
                S3_PATH_BLOG: ${S3_PATH_BLOG}
                S3_BUCKET_PHOTOGRAPHY: ${S3_BUCKET_PHOTOGRAPHY}
                S3_PATH_PHOTOGRAPHY: ${S3_PATH_PHOTOGRAPHY}
                S3_BUCKET_EXPERIENCE: ${S3_BUCKET_EXPERIENCE}
                S3_PATH_EXPERIENCE: ${S3_PATH_EXPERIENCE}
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            NODE_ENV: production
        restart: unless-stopped
